project_id = "opzypedbkufjiprbhogl"

[functions.analyze-url]
verify_jwt = true

[functions.analyze-image]
verify_jwt = true

[functions.analyze-file]
verify_jwt = true

[functions.generate-embedding]
verify_jwt = true

[functions.generate-tag-icon]
verify_jwt = true

[functions.chat-with-library]
verify_jwt = true
